Repository ember-cli-sentry/ember-cli-sentry, pull requests merged in 2018-09, with the labels that each got.

#141 Use console rather than Ember.Logger
  .eslintrc.js
  addon/index.js
  addon/services/raven.js
Labels: enhancement

#143 Fix CI builds
  package.json
  yarn.lock
Labels: internal

#142 Drop node v4 support
  .travis.yml
  package.json
Labels: breaking

#97 Do not throw error/message when raven disabled
  addon/services/raven.js
Labels: breaking, enhancement

#146 yarn: Add `integrity` hashes
  yarn.lock
Labels: internal

#145 Update `lerna-changelog` to v0.8.0
  package.json
  yarn.lock
Labels: internal

#149 Update `raven-js` to v3.27.0
  package.json
  yarn.lock
Labels: enhancement

#148 Update `broccoli-merge-trees` to v3.0.1
  package.json
  yarn.lock
Labels: internal

#150 Remove unused `ember-cli-app-version` dev dependency
  package.json
  yarn.lock
Labels: internal

#152 Remove unused `ember-cli-release` dev dependency
  package.json
  yarn.lock
Labels: internal

#153 Update `ember-cli-babel` to v7.1.2
  README.md
  package.json
  yarn.lock
Labels: breaking

#140 Mark raven-shim as an ES module
  vendor/raven-shim.js
Labels: enhancement
